---
- name: Restart Docker Artifactory
  docker:
    name: '{{ docker_artifactory_name }}'
    image: '{{ docker_artifactory_image }}'
    hostname: '{{ docker_artifactory_hostname }}'
    env: '{{ docker_artifactory_env }}'
    ports: '{{ docker_artifactory_ports }}'
    volumes: '{{ docker_artifactory_volumes }}'
    state: started
    #restart: True
